apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-one  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-one
  template:
    metadata:
      labels:
        app: helloworld-one
    spec:
      containers:
      - name: helloworld-one
        image: e880613/hello-app:v1
        ports:
        - containerPort: 8080
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: helloworld-one  
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: helloworld-one