apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld  
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: e880613/hello-app:v1
        ports:
        - containerPort: 8080